### ISSUE TITLE
I lost my database in UI

### ISSUE THREAD

**Issue by txx18** [neo4j-devtools/neo4j-desktop#100]
hello, .
Yesterday I accidentally restarted my computer,  and I found that some of my databases were missing.
You can see I have only 5 databases here, but there are 8 directories in "dbmss".
![Snipaste_2020-12-27_18-17-59](https://user-images.githubusercontent.com/57362817/103168653-17564980-4870-11eb-95ad-c27d675aea59.png)
![Snipaste_2020-12-27_18-20-50](https://user-images.githubusercontent.com/57362817/103168712-79af4a00-4870-11eb-8ac2-8d22b2ccdc73.png)

That mean I need to reload my another 3 databases, even if they may be broken.
I would appreciate your help.

other information: 
1. some of the databases were cloned from another orignally, and I use the original one for back up.
2. I renamed them when a database is online.

system inforamtion:
1. os: windows 10 v2004
2. neo4j version: 4.2.0 & 4.2.1
3. neo4j destop verson: 1.3.11

**Comment by nglgzz** [comment]
Hi @txx18, could you post the content of the `databases.json` file used by Desktop? You can find it by following these steps:

- Press ctrl+k.
- Type logs and press enter.
- A directory will open up. Open the persist folder inside it.
- You should be able to see the `databases.json` file there.

Not really sure what happened here, but I suspect the missing DBMSs are just missing in that file.

**Comment by txx18** [comment]
Thank you very much! I hava re-import my data. Next time I will check databases.json.

**Comment by nglgzz** [comment]
Thank you for the update, and sorry for the trouble!

I'm still not sure what could have caused this, but in Neo4j Desktop 1.4.0 we added a fix for Desktop removing entries from that file in specific circumstances, so this shouldn't happen again.
