### ISSUE TITLE
Scrollbar appearing in middle of input box

### ISSUE THREAD

**Issue by whatSocks** [neo4j-devtools/neo4j-desktop#93]
<img width="1203" alt="Screen Shot 2020-09-28 at 5 10 29 PM" src="https://user-images.githubusercontent.com/2731744/94486502-83f87400-01ad-11eb-9d60-e4f791862ae5.png">

To reproduce:

```
:play https://guides.neo4j.com/graph-examples/disease-outbreak-on-a-space-station/graph_guide
```

Tap next until you get to page 4
Pin the guide
Tap and play on the code blocks until you get to the bottom one
See UI

**Comment by OskarDamkjaer** [comment]
Thanks for reporting! This is a neo4j-browser issue, could you reopen it there? I can't transfer it since it's under different github organisations

**Comment by jk05** [comment]
@whatSocks I will close it here on neo4j-desktop. I couldn't see it reopened on neo4j-browser.
